#! /bin/sh

# Hotkey Daemon
sxhkd &

# Compositor
compton -b &

# Painels
~/.config/polybar/launch.sh &

# Wallpaper
feh --bg-fill ~/Pictures/wallpaper/wall\ 6.jpg

# Notification Daemon
~/.config/scripts/battery-status.sh &

# Music Player Daemon
mpd &

# Auto lockscreen
xautolock -time 10 -locker 'betterlockscreen -l' &

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc config click_to_focus false
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width         3
bspc config window_gap           10

bspc config top_padding 20
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0

bspc config normal_border_color   "#222222"
bspc config focused_border_color  "#444444"
bspc config presel_feedback_color "#444444"

# RULES
bspc rule -a firefox desktop=^1 follow=on
bspc rule -a qutebrowser desktop=^1 follow=on
bspc rule -a st-256color desktop=^2 follow=on
bspc rule -a vim desktop=^3 follow=on
bspc rule -a Gvim desktop=^3 follow=on
bspc rule -a Sublime_text desktop=^3 follow=on
bspc rule -a RStudio desktop=^3 follow=on
bspc rule -a Thunar desktop=^4 follow=on
bspc rule -a Ranger desktop=^4 follow=on
bspc rule -a MuPDF desktop=^5 follow=on
bspc rule -a Soffice desktop=^5 follow=on
bspc rule -a libreoffice-startcenter desktop=^5 follow=on
bspc rule -a Gimp-2.10 desktop=^5 follow=on
bspc rule -a TelegramDesktop desktop=^6 follow=off
bspc rule -a Ncmpcpp desktop=^7 follow=on
bspc rule -a 'VirtualBox Manager' desktop=^8 follow=on
bspc rule -a Steam desktop=^8 follow=off
bspc rule -a qBittorrent desktop=^9 follow=on

bspc rule -a firefox:Places state=floating center=on
bspc rule -a Nitrogen state=floating center=on
bspc rule -a Pavucontrol state=floating center=on
bspc rule -a Qalculate-gtk  state=floating center=on
bspc rule -a screencast state=floating center=on
